# Generated by Django 4.2.1 on 2023-05-19 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=50, unique=True)),
                ('book_name', models.CharField(max_length=100)),
                ('book_grade', models.CharField(max_length=15)),
                ('storage', models.IntegerField()),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=75)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='person_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.IntegerField(unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=15)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='my_app.parent')),
            ],
            options={
                'db_table': 'pupil',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book1', to='my_app.book')),
                ('book_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book2', to='my_app.book')),
                ('book_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book3', to='my_app.book')),
                ('book_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book4', to='my_app.book')),
                ('book_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book5', to='my_app.book')),
                ('book_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book6', to='my_app.book')),
                ('book_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book7', to='my_app.book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='renter', to='my_app.pupil')),
            ],
            options={
                'db_table': 'rent',
            },
        ),
    ]
