# Generated by Django 4.2.1 on 2023-05-21 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='personal_id',
            new_name='parent_id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='book_7',
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='person_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book2', to='my_app.book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book3', to='my_app.book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book4', to='my_app.book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book_5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book5', to='my_app.book'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book_6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book6', to='my_app.book'),
        ),
    ]
