# Generated by Django 4.2.1 on 2023-06-01 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_personal_id_parent_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='only numbers from 0 to 9 are allowed', regex='^[0-9]+$')]),
        ),
    ]
