# Generated by Django 4.2.1 on 2023-06-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_parent_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='book_10',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book10', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_11',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book11', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_12',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book12', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_13',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book13', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_14',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book14', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_15',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book15', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_16',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book16', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_17',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book17', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_7',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book7', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book8', to='my_app.book'),
        ),
        migrations.AddField(
            model_name='rent',
            name='book_9',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book9', to='my_app.book'),
        ),
    ]
