# Generated by Django 4.2.1 on 2023-06-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rent_book_10_rent_book_11_rent_book_12_rent_book_13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.RESTRICT, related_name='renter', to='my_app.pupil'),
        ),
    ]
