# Generated by Django 4.2.1 on 2023-06-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_rent_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='book_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rent_book1', to='my_app.book'),
        ),
    ]
