# Generated by Django 4.2.1 on 2023-07-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_rent_book_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
